/*
 * Lukas Krampitz
 * Oct 20, 2020
 * UI for a Library
 */
package searchingexercise1;

import java.io.File;
import java.io.FileNotFoundException;
import java.util.ArrayList;
import java.util.Scanner;

/**
 *
 * @author Tacitor
 */
public class LibraryUI extends javax.swing.JFrame {
    
    private static ArrayList<Book> books = loadDatabase();
    private static int binaryCounter;

    /**
     * Creates new form LibraryUI
     */
    public LibraryUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainLbl = new javax.swing.JLabel();
        decriptionLbl = new javax.swing.JLabel();
        refNumPromptLbl = new javax.swing.JLabel();
        refNumTxtBox = new javax.swing.JTextField();
        searchBtn = new javax.swing.JButton();
        linearLbl = new javax.swing.JLabel();
        binaryLbl = new javax.swing.JLabel();
        binaryTxt = new javax.swing.JTextField();
        linearTxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Childrens's Classics");

        mainLbl.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        mainLbl.setForeground(new java.awt.Color(255, 0, 0));
        mainLbl.setText("Childrens's Classics");

        decriptionLbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        decriptionLbl.setText("This program will find the title of a book according to the library reference number");

        refNumPromptLbl.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        refNumPromptLbl.setText("Enter the refernce number:");

        searchBtn.setText("Find It!");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        linearLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        linearLbl.setText("Linear Search");

        binaryLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        binaryLbl.setText("Binary Search");

        binaryTxt.setEditable(false);
        binaryTxt.setBackground(new java.awt.Color(255, 255, 255));
        binaryTxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        linearTxt.setEditable(false);
        linearTxt.setBackground(new java.awt.Color(255, 255, 255));
        linearTxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/searchingexercise1/bears.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(linearLbl)
                            .addComponent(binaryLbl))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(linearTxt)
                            .addComponent(binaryTxt)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mainLbl)
                            .addComponent(decriptionLbl)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(refNumPromptLbl)
                                .addGap(87, 87, 87)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(searchBtn)
                                    .addComponent(refNumTxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(59, 59, 59)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(mainLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(decriptionLbl)
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(refNumPromptLbl)
                            .addComponent(refNumTxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(searchBtn)
                        .addGap(28, 28, 28))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(linearLbl)
                    .addComponent(linearTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(binaryLbl)
                    .addComponent(binaryTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        // TODO add your handling code here:
        String error = "ERROR! Please enter a number";

        //Check for blank ref number      
        if (refNumTxtBox.getText().equals("")) {
            setOutput(error);
        } else {
            //check for back int
            try {
                Integer.parseInt(refNumTxtBox.getText());
                linearTxt.setText(linSrch(books, Integer.parseInt(refNumTxtBox.getText())));
                //reset the binary counter
                binaryCounter = 1;
                binaryTxt.setText(binSrch(books, Integer.parseInt(refNumTxtBox.getText()), 0, books.size()));
            } catch (NumberFormatException e) {
                setOutput(error);
            }
        }


    }//GEN-LAST:event_searchBtnActionPerformed

    public void setOutput(String msg) {
        linearTxt.setText(msg);
        binaryTxt.setText(msg);
    }
    
    public String binSrch(ArrayList<Book> books, int refNum, int left, int right) {
        binaryCounter++; //count a search
        int middle;
        //check if the the array has been completly searched
        if (left > right) {
            return srchFail(refNum);
        }
        //find the middle
        middle = (left + right) / 2;
        //check if the book has been found
        if (books.get(middle).getRef() == refNum) {
            return srchSuccess(books.get(middle).getTitle(), binaryCounter);
        }
        //since no book found and there is still array left over cut in half and try again
        //pick a side to keep
        if (refNum > books.get(middle).getRef()) {
            return binSrch(books, refNum, middle + 1, right);
        } else {
            return binSrch(books, refNum, left, middle - 1);
        }
    }
    
    public String linSrch(ArrayList<Book> books, int refNum) {
        for (int i = 0; i < books.size(); i++) {
            if (books.get(i).getRef() == refNum) {
                return srchSuccess(books.get(i).getTitle(), (i+1));
            }
        }
        
        return srchFail(refNum);
    }
    
    public String srchSuccess(String title, int num) {
        return "Found: " + title + ", " + num + " books processed";
    }
    
    public String srchFail(int refNum) {
        return "Book #" + refNum + " not found.";
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LibraryUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LibraryUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LibraryUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LibraryUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>


        //System.out.println(books);

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LibraryUI().setVisible(true);
            }
        });
    }

    protected static ArrayList<Book> loadDatabase() {
        ArrayList<Book> books = new ArrayList();
        String adr = "src\\searchingexercise1\\BookList.txt";

        try {
            File file = new File(adr);
            Scanner scanner = new Scanner(file);

            //load up
            while (scanner.hasNextLine()) {
                Book book = new Book(Integer.parseInt(scanner.nextLine()), scanner.nextLine());

                books.add(book);
            }

        } catch (FileNotFoundException e) {
            System.out.println("Error: " + e);
        }

        return books;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel binaryLbl;
    private javax.swing.JTextField binaryTxt;
    private javax.swing.JLabel decriptionLbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel linearLbl;
    private javax.swing.JTextField linearTxt;
    private javax.swing.JLabel mainLbl;
    private javax.swing.JLabel refNumPromptLbl;
    private javax.swing.JTextField refNumTxtBox;
    private javax.swing.JButton searchBtn;
    // End of variables declaration//GEN-END:variables
}
